export const FINE_W = 4;
export const FINE_H = 3;

export const st = {
  panels: [],
  sunData: null,
  historyCache: {},
  sliderActive: false,
  selectedDate: null,
  chartRange: 'today',
  lastChartPoints: [],
  gridChartRange: 'today',
  lastGridPoints: [],
  gridHasExport: false,
  showGridChart: true,
  gridAvailable: false,
  refreshTimer: null,
  refreshInterval: 30000,
  panelTarget: null,
  panelChartRange: '30d',
  batteryAvailable: false,
  leftPanelTab: 'grid',
  batteryChartRange: 'today',
  batteryChartType: 'soc',
  lastBatteryPoints: [],
  batteryStatus: null,
  batteryList: [],
  selectedBatteryIdx: 0,
  gridLayout: null,
  editMode: false,
  editPositions: {},
  editRotations: {},
  editRows: 12,
  editCols: 64,
  dragEntityId: null,
  dragLabelId: null,
  dragOffsetRow: 0,
  dragOffsetCol: 0,
  editLabels: [],
  bankDefaultRotation: 0,
  nameStrip: [],
  showPanelNames: true,
  minAvgW: 5,
  invertBatteryPower: false,
  isPlaying: false,
  playbackSpeed: 1,
  playbackTimer: null,
  weather: null,
};
